### ISSUE TITLE
Error in publish all cloud

### ISSUE THREAD

**Issue by izengpan** [shichaoy/pop_up_slam#1]
hello, thanks for your great work.
I run the pop_up_slam, and the Rviz came out successfully, but the terminal showed error like:
 
[ERROR] [1542117455.104213710, 1454368534.284882313]: publish all cloud
[rosbag-5] process has finished cleanly
log file: /home/zp/.ros/log/0255265a-e74c-11e8-b148-107b4490cde3/rosbag-5*.log
[ERROR] [1542117457.879948980, 1454368534.889248398]: finish pub cloud num 106

Have you ever met this problem?
Thanks for your reply!

**Comment by shichaoy** [comment]
Hi, sorry for the confusion. That's not an error. I just want to show a stream in red to mark it. You can find it in the main file. I will change to another color in my future commits. thanks.

**Comment by izengpan** [comment]
Thanks for your quick and patient reply!
 I have got it.
