### ISSUE TITLE
problem about the total number of output of pose

### ISSUE THREAD

**Issue by izengpan** [shichaoy/pop_up_slam#10]
hello, shichaoy
I was meant to print the pose of every keyframe, but as a result, when the terminal screen showed that we have processed more than 200 keyframes, the final pose.txt only includs 82 poses, which is the exact number of the dataset you used. However, I have changed the dataset. 
So, I'm writing to ask about this problem...
Looking forward to your reply.

**Comment by shichaoy** [comment]
hi sorry for the late reply. I think you probably need to change the parameter of last_frame_id in ```plane_3d_tum_far.yaml``` for your own data. now it is 80 (for my dataset). In ```main_3d.cpp```, you will find that when frameId equal last_frame_id, it will save poses to txt.

**Comment by izengpan** [comment]
Ok.
Thanks! it is solved.
