### ISSUE TITLE
pop_polygon in rviz can not received images.

### ISSUE THREAD

**Issue by zengyawen13** [shichaoy/pop_up_slam#22]
sorry to interrupt.
I had this problem running this program：pop_polygon in rviz can not received 
I have no ideal how to solve this problem.
Thank you for your helping 
- images.
![2020-06-07 17-13-00屏幕截图](https://user-images.githubusercontent.com/66003264/83965217-8d9b5a80-a8e4-11ea-8943-afbaf7cbe423.png)
![2020-06-07 17-13-48屏幕截图](https://user-images.githubusercontent.com/66003264/83965218-91c77800-a8e4-11ea-83fd-d8be66374c49.png)

**Comment by zengyawen13** [comment]
I solved it successfully！！！！

**Comment by jiashoujun** [comment]
Hellow! I meet same problem with you. Could you tell me how to deal with it?

**Comment by zengyawen13** [comment]
> Hellow! I meet same problem with you. Could you tell me how to deal with it?

Actually, I don't remember very well. The data path under this file should be changed to an absolute path.
/pop_up_wall/src/popup_plane_main.cpp,line69-70。
` std::string raw_img_name = package_path+"./data/rgb_"+std::string(frame_index_c)+".png";
  std::string label_img_name = package_path+"./data/label_"+std::string(frame_index_c)+".png";`
