### ISSUE TITLE
The corridor scene has many small facets that have not been pieced together

### ISSUE THREAD

**Issue by szx1995** [shichaoy/pop_up_slam#25]
May I ask if there are many small faces in my corridor scene, instead of long ones pieced together
![2024-05-31 09-45-15 的屏幕截图](https://github.com/shichaoy/pop_up_slam/assets/165112521/3f3ece27-1aac-4500-85bc-ea444d9242ae)

**Comment by XiaoElMacho** [comment]
hi @szx1995  How did you get the segmentation masks of the corridor dataset? Also, could you share the launch file for this one? many thanks

**Comment by szx1995** [comment]
I adopted the author's answer about “Excuse me,can you tell me where the picture of the ground segmentation(label_img) comes from?&nbsp;#13”.



I made it using segNet.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shichaoy/pop_up_slam"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月13日(星期四) 晚上10:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shichaoy/pop_up_slam] The corridor scene has many small facets that have not been pieced together (Issue #25)





 
hi @szx1995  How did you get the segmentation masks of the corridor dataset? Also, could you share the launch file for this one? many thanks
