### ISSUE TITLE
question about the dataset

### ISSUE THREAD

**Issue by izengpan** [shichaoy/pop_up_slam#4]
hello, shichaoy.
I have run the codes with tum_far_preproc_tf.bag successfully, but when I change the .bag file into others, such as rgbd_dataset_freiburg3_structure_notexture_far.bag, the whole codes won't give any error, but the RVIZ won't show anything. There is nothing out. So, I'm writing to ask whether the tum_far_preproc_tf.bag actually is the .bag file that has been pre-processed one? And how can I make some tests on other data series?
Thanks for you reply.

**Comment by shichaoy** [comment]
Hi, thanks for the interest. yes, the bag has already been processed and created/recorded by me. You can use   ```rosbag info tum_far_preproc_tf.bag``` to see required messages inside the bag or in the main function of ```main_3d.cpp```: rgb image and cnn ground segmentation image. You can use many other cnn segmentation algorithm.  /tf topic is optional.   The code is mainly for demonstration, and may not work for general scenarios.
