### ISSUE TITLE
catkin_make -j4 error

### ISSUE THREAD

**Issue by hitzhang** [shichaoy/pop_up_slam#7]
/popup_ws/src/pop_up_slam/dependency/numpy_opencv/src/np_opencv_converter.cpp:12:2: error: return-statement with a value, in function returning 'void' [-fpermissive]
   import_array();

/popup_ws/src/pop_up_slam/dependency/numpy_opencv/src/utils/conversion.cpp:200:4: error: return-statement with a value, in function returning 'void' [-fpermissive]
     import_array();

**Comment by shichaoy** [comment]
Hi, that package is from external library ```https://github.com/spillai/numpy-opencv-converter```. I googled the error  "in function returning 'void' [-fpermissive] import_array()", found that it may be due to python3 (I used 2.7). Some relevant post ```https://github.com/clemenscorny/brisk/issues/3``` might help.
